/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BrandKitsRouteImport } from './routes/brand-kits'
import { Route as NewRouteImport } from './routes/new'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as PresentationsIndexRouteImport } from './routes/presentations.index'
import { Route as PresentationsPresentationIdRouteImport } from './routes/presentations.$presentationId'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as PresentationsPresentationIdAudienceRouteImport } from './routes/presentations_.$presentationId.audience'
import { Route as PresentationsPresentationIdEditorRouteImport } from './routes/presentations_.$presentationId.editor'
import { Route as PresentationsPresentationIdPresenterRouteImport } from './routes/presentations_.$presentationId.presenter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitsRoute = BrandKitsRouteImport.update({
  id: '/brand-kits',
  path: '/brand-kits',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsPresentationIdRoute =
  PresentationsPresentationIdRouteImport.update({
    id: '/presentations/$presentationId',
    path: '/presentations/$presentationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsPresentationIdAudienceRoute =
  PresentationsPresentationIdAudienceRouteImport.update({
    id: '/presentations_/$presentationId/audience',
    path: '/presentations/$presentationId/audience',
    getParentRoute: () => rootRouteImport,
  } as any)
const PresentationsPresentationIdEditorRoute =
  PresentationsPresentationIdEditorRouteImport.update({
    id: '/presentations_/$presentationId/editor',
    path: '/presentations/$presentationId/editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const PresentationsPresentationIdPresenterRoute =
  PresentationsPresentationIdPresenterRouteImport.update({
    id: '/presentations_/$presentationId/presenter',
    path: '/presentations/$presentationId/presenter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-kits': typeof BrandKitsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/review/$token': typeof ReviewTokenRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/presentations/$presentationId/audience': typeof PresentationsPresentationIdAudienceRoute
  '/presentations/$presentationId/editor': typeof PresentationsPresentationIdEditorRoute
  '/presentations/$presentationId/presenter': typeof PresentationsPresentationIdPresenterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-kits': typeof BrandKitsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/review/$token': typeof ReviewTokenRoute
  '/presentations': typeof PresentationsIndexRoute
  '/presentations/$presentationId/audience': typeof PresentationsPresentationIdAudienceRoute
  '/presentations/$presentationId/editor': typeof PresentationsPresentationIdEditorRoute
  '/presentations/$presentationId/presenter': typeof PresentationsPresentationIdPresenterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-kits': typeof BrandKitsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/review/$token': typeof ReviewTokenRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/presentations_/$presentationId/audience': typeof PresentationsPresentationIdAudienceRoute
  '/presentations_/$presentationId/editor': typeof PresentationsPresentationIdEditorRoute
  '/presentations_/$presentationId/presenter': typeof PresentationsPresentationIdPresenterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/brand-kits'
    | '/new'
    | '/settings'
    | '/templates'
    | '/invite/$token'
    | '/presentations/$presentationId'
    | '/review/$token'
    | '/presentations/'
    | '/presentations/$presentationId/audience'
    | '/presentations/$presentationId/editor'
    | '/presentations/$presentationId/presenter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/brand-kits'
    | '/new'
    | '/settings'
    | '/templates'
    | '/invite/$token'
    | '/presentations/$presentationId'
    | '/review/$token'
    | '/presentations'
    | '/presentations/$presentationId/audience'
    | '/presentations/$presentationId/editor'
    | '/presentations/$presentationId/presenter'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/brand-kits'
    | '/new'
    | '/settings'
    | '/templates'
    | '/invite/$token'
    | '/presentations/$presentationId'
    | '/review/$token'
    | '/presentations/'
    | '/presentations_/$presentationId/audience'
    | '/presentations_/$presentationId/editor'
    | '/presentations_/$presentationId/presenter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BrandKitsRoute: typeof BrandKitsRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PresentationsPresentationIdRoute: typeof PresentationsPresentationIdRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
  PresentationsPresentationIdAudienceRoute: typeof PresentationsPresentationIdAudienceRoute
  PresentationsPresentationIdEditorRoute: typeof PresentationsPresentationIdEditorRoute
  PresentationsPresentationIdPresenterRoute: typeof PresentationsPresentationIdPresenterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kits': {
      id: '/brand-kits'
      path: '/brand-kits'
      fullPath: '/brand-kits'
      preLoaderRoute: typeof BrandKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/presentations'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/$presentationId': {
      id: '/presentations/$presentationId'
      path: '/presentations/$presentationId'
      fullPath: '/presentations/$presentationId'
      preLoaderRoute: typeof PresentationsPresentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations_/$presentationId/audience': {
      id: '/presentations_/$presentationId/audience'
      path: '/presentations/$presentationId/audience'
      fullPath: '/presentations/$presentationId/audience'
      preLoaderRoute: typeof PresentationsPresentationIdAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations_/$presentationId/editor': {
      id: '/presentations_/$presentationId/editor'
      path: '/presentations/$presentationId/editor'
      fullPath: '/presentations/$presentationId/editor'
      preLoaderRoute: typeof PresentationsPresentationIdEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations_/$presentationId/presenter': {
      id: '/presentations_/$presentationId/presenter'
      path: '/presentations/$presentationId/presenter'
      fullPath: '/presentations/$presentationId/presenter'
      preLoaderRoute: typeof PresentationsPresentationIdPresenterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BrandKitsRoute: BrandKitsRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  InviteTokenRoute: InviteTokenRoute,
  PresentationsPresentationIdRoute: PresentationsPresentationIdRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
  PresentationsPresentationIdAudienceRoute:
    PresentationsPresentationIdAudienceRoute,
  PresentationsPresentationIdEditorRoute:
    PresentationsPresentationIdEditorRoute,
  PresentationsPresentationIdPresenterRoute:
    PresentationsPresentationIdPresenterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
