/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BrandKitsRouteImport } from './routes/brand-kits'
import { Route as NewRouteImport } from './routes/new'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PresentationsIndexRouteImport } from './routes/presentations.index'
import { Route as PresentationsPresentationIdRouteImport } from './routes/presentations.$presentationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitsRoute = BrandKitsRouteImport.update({
  id: '/brand-kits',
  path: '/brand-kits',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsPresentationIdRoute =
  PresentationsPresentationIdRouteImport.update({
    id: '/presentations/$presentationId',
    path: '/presentations/$presentationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-kits': typeof BrandKitsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-kits': typeof BrandKitsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/presentations': typeof PresentationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/brand-kits': typeof BrandKitsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/brand-kits'
    | '/new'
    | '/settings'
    | '/templates'
    | '/presentations/$presentationId'
    | '/presentations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/brand-kits'
    | '/new'
    | '/settings'
    | '/templates'
    | '/presentations/$presentationId'
    | '/presentations'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/brand-kits'
    | '/new'
    | '/settings'
    | '/templates'
    | '/presentations/$presentationId'
    | '/presentations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BrandKitsRoute: typeof BrandKitsRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  PresentationsPresentationIdRoute: typeof PresentationsPresentationIdRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kits': {
      id: '/brand-kits'
      path: '/brand-kits'
      fullPath: '/brand-kits'
      preLoaderRoute: typeof BrandKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/presentations'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/$presentationId': {
      id: '/presentations/$presentationId'
      path: '/presentations/$presentationId'
      fullPath: '/presentations/$presentationId'
      preLoaderRoute: typeof PresentationsPresentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BrandKitsRoute: BrandKitsRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  PresentationsPresentationIdRoute: PresentationsPresentationIdRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
